package com.securevault.app.security

import android.security.keystore.KeyPermanentlyInvalidatedException
import android.util.Base64
import javax.crypto.AEADBadTagException
import javax.crypto.Cipher
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * Performs AES-256-GCM in-memory encryption and decryption of vault fields.
 *
 * Spec refs:
 *   - Technical_Requirements.md §2 — "AES-GCM (AES Encryption) 256-bit" in stack
 *   - Security_Requirements.md §4 — "Encrypt the `password` field using
 *     AES-GCM-256 on the client device prior to synchronization" [MUST]
 *   - SRS FR-VAULT-02 — "encrypt the password field in-memory using AES-256-GCM
 *     via the VMK before writing it to the local SQLite/Room database"
 *   - SRS NFR-PERF-03 — "AES-GCM-256 decryption must complete in < 100ms"
 *   - Testing_Strategy.md Part 1 §1 — CryptographyHelper unit test spec:
 *       Happy Path: plaintext + 256-bit VMK → Base64 ciphertext + 12-byte IV
 *       Boundary: empty/null → IllegalArgumentException
 *       Invalid: corrupted ciphertext → AEADBadTagException
 *       Key invalidation → KeyPermanentlyInvalidatedException
 *   - Technical_Requirements.md §8 — Hard constraint: VMK must NEVER be written
 *     to persistent storage. Caller is responsible for zeroing byte arrays after use.
 *
 * Output format: Base64(IV_12_bytes || ciphertext)
 * The IV is prepended to the ciphertext so a single opaque string can be stored
 * in the database — no separate IV column required.
 *
 * Thread safety: stateless object. Cipher instances are created per call.
 */
object CryptographyHelper {

    private const val TRANSFORMATION = "AES/GCM/NoPadding"
    private const val GCM_TAG_LENGTH_BITS = 128     // 16-byte authentication tag
    const val GCM_IV_LENGTH_BYTES = 12              // Standard 96-bit IV for AES-GCM

    // -------------------------------------------------------------------------
    // Encryption
    // -------------------------------------------------------------------------

    /**
     * Encrypts [plaintext] using AES-256-GCM with the provided [key].
     *
     * @param plaintext The plaintext string to encrypt (e.g. the raw password value).
     * @param key       A 256-bit AES SecretKey from the Android Keystore or a VMK.
     * @return Base64-encoded string of the form: Base64(IV || ciphertext)
     *
     * @throws IllegalArgumentException if [plaintext] is blank.
     * @throws KeyPermanentlyInvalidatedException if biometric enrollment changed.
     *
     * Memory safety: the intermediate byte arrays are zeroed after use per
     * Technical_Requirements.md §8 hard constraint against plaintext persistence.
     */
    @Throws(IllegalArgumentException::class, KeyPermanentlyInvalidatedException::class)
    fun encrypt(plaintext: String, key: SecretKey): String {
        require(plaintext.isNotEmpty()) {
            "CryptographyHelper.encrypt: plaintext must not be empty"
        }

        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, key)

        val iv = cipher.iv          // 12-byte IV generated by the Cipher (randomized)
        check(iv.size == GCM_IV_LENGTH_BYTES) {
            "Expected 12-byte IV, got ${iv.size}"
        }

        val plaintextBytes = plaintext.toByteArray(Charsets.UTF_8)
        val ciphertext = cipher.doFinal(plaintextBytes)

        // Zero plaintext bytes immediately after encryption
        plaintextBytes.fill(0)

        // Combine IV + ciphertext into a single byte array for storage
        val combined = ByteArray(GCM_IV_LENGTH_BYTES + ciphertext.size)
        System.arraycopy(iv, 0, combined, 0, GCM_IV_LENGTH_BYTES)
        System.arraycopy(ciphertext, 0, combined, GCM_IV_LENGTH_BYTES, ciphertext.size)

        return Base64.encodeToString(combined, Base64.NO_WRAP)
    }

    // -------------------------------------------------------------------------
    // Decryption
    // -------------------------------------------------------------------------

    /**
     * Decrypts a Base64-encoded [encryptedData] string (IV || ciphertext) using
     * AES-256-GCM with the provided [key].
     *
     * @param encryptedData Base64 string produced by [encrypt].
     * @param key           The same 256-bit AES SecretKey used to encrypt.
     * @return The original plaintext string.
     *
     * @throws IllegalArgumentException if [encryptedData] is blank or too short.
     * @throws AEADBadTagException if the ciphertext is corrupted or the key is wrong.
     * @throws KeyPermanentlyInvalidatedException if biometric enrollment changed.
     *
     * Memory safety: intermediate decrypted byte arrays are zeroed after String
     * construction per Technical_Requirements.md §8.
     */
    @Throws(
        IllegalArgumentException::class,
        AEADBadTagException::class,
        KeyPermanentlyInvalidatedException::class
    )
    fun decrypt(encryptedData: String, key: SecretKey): String {
        require(encryptedData.isNotEmpty()) {
            "CryptographyHelper.decrypt: encryptedData must not be empty"
        }

        val combined = Base64.decode(encryptedData, Base64.NO_WRAP)

        require(combined.size > GCM_IV_LENGTH_BYTES) {
            "CryptographyHelper.decrypt: data too short to contain IV + ciphertext"
        }

        val iv = combined.copyOfRange(0, GCM_IV_LENGTH_BYTES)
        val ciphertext = combined.copyOfRange(GCM_IV_LENGTH_BYTES, combined.size)

        val cipher = Cipher.getInstance(TRANSFORMATION)
        val spec = GCMParameterSpec(GCM_TAG_LENGTH_BITS, iv)
        cipher.init(Cipher.DECRYPT_MODE, key, spec)

        // AEADBadTagException thrown here if tag verification fails (corrupted data)
        val decryptedBytes = cipher.doFinal(ciphertext)

        val result = String(decryptedBytes, Charsets.UTF_8)

        // Zero decrypted bytes immediately after String construction
        decryptedBytes.fill(0)
        iv.fill(0)

        return result
    }

    // -------------------------------------------------------------------------
    // SQLCipher passphrase derivation
    // -------------------------------------------------------------------------

    /**
     * Derives a 32-byte (256-bit) SQLCipher passphrase by encrypting a fixed
     * sentinel value with the DB key from the Keystore.
     *
     * The sentinel is a deterministic label — the actual entropy comes from the
     * AES-GCM encryption key stored in the Keystore (256-bit secure random).
     * The resulting ciphertext byte array is used directly as the SQLCipher
     * passphrase, satisfying Security_Requirements.md §9.1 256-bit entropy.
     *
     * This approach means:
     *   1. The passphrase is reproducible on the same device (same Keystore key).
     *   2. It is different on every device (Keystore keys are device-bound).
     *   3. The Keystore key itself never leaves the TEE.
     *
     * @param dbKey The AES SecretKey from KeystoreManager (DB_KEY_ALIAS).
     * @return Byte array to pass to SupportFactory. Caller MUST zero this array
     *         immediately after AppDatabase.getInstance() returns.
     */
    fun deriveDatabasePassphrase(dbKey: SecretKey): ByteArray {
        val sentinel = "securevault_db_passphrase_v1"
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, dbKey)

        val iv = cipher.iv
        val ciphertext = cipher.doFinal(sentinel.toByteArray(Charsets.UTF_8))

        // Return IV + ciphertext as the passphrase — always 12 + ciphertext_len bytes
        // SQLCipher accepts any non-empty byte array as a passphrase
        val passphrase = ByteArray(iv.size + ciphertext.size)
        System.arraycopy(iv, 0, passphrase, 0, iv.size)
        System.arraycopy(ciphertext, 0, passphrase, iv.size, ciphertext.size)

        iv.fill(0)
        return passphrase
        // NOTE: The returned passphrase array MUST be zeroed by the caller after use.
    }
}
