package com.securevault.app.data

import android.content.Context
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.sqlite.db.SupportSQLiteOpenHelper
import com.securevault.app.data.entities.CategoryEntity
import com.securevault.app.data.entities.DeviceSessionEntity
import com.securevault.app.data.entities.HistoryEntity
import com.securevault.app.data.entities.PasswordEntity
import com.securevault.app.data.entities.SyncQueueEntity
import com.securevault.app.data.entities.UserEntity
import com.securevault.app.data.dao.UserDao
import com.securevault.app.data.dao.CategoryDao
import com.securevault.app.data.dao.VaultDao
import com.securevault.app.data.dao.HistoryDao
import com.securevault.app.data.dao.SyncQueueDao
import net.sqlcipher.database.SQLiteDatabaseHook
import net.sqlcipher.database.SupportFactory

/**
 * Room database singleton for SecureVault local encrypted storage.
 *
 * Spec refs:
 *   - Architecture.md ADR-02 — Room + SQLCipher (Option B: full DB encryption)
 *   - SRS FR-SYNC-01, NFR-SEC-01 — AES-256-CBC encrypted local database
 *   - Security_Requirements.md §4 — local database encryption via SQLCipher
 *   - Security_Requirements.md §9.1 — PRAGMA secure_delete=ON to prevent
 *     plaintext remnants in temporary directories
 *   - Database_Schema.md §7 — migration strategy using addMigrations()
 *   - Database_Schema.md §2 — all 6 entity tables registered
 *
 * SQLCipher passphrase is provided by KeystoreManager (implemented in task-003).
 * This class is intentionally decoupled from key derivation — the caller
 * passes in the passphrase byte array.
 *
 * Thread safety: getInstance() is synchronized. All DB access must occur
 * on background threads via Kotlin coroutines (Room enforces this).
 */
@Database(
    entities = [
        UserEntity::class,
        PasswordEntity::class,
        CategoryEntity::class,
        HistoryEntity::class,
        DeviceSessionEntity::class,
        SyncQueueEntity::class
    ],
    version = 1,
    exportSchema = true     // Required for Room migration verification tests
)
abstract class AppDatabase : RoomDatabase() {

    abstract fun userDao(): UserDao

    /** Category DAO — task-010, Database_Schema.md §2.4 */
    abstract fun categoryDao(): CategoryDao

    /** Vault DAO — task-011, Database_Schema.md §2.2/§2.3 */
    abstract fun vaultDao(): VaultDao

    /** History DAO — task-012, Database_Schema.md §2.3 */
    abstract fun historyDao(): HistoryDao

    /** Sync Queue DAO — task-021, Database_Schema.md §2.6 */
    abstract fun syncQueueDao(): SyncQueueDao

    // DAO accessors — implementations are generated by Room's kapt processor.
    // Full DAO interfaces are created in their respective tasks:
    //   task-002: schema only (no DAO implementations yet)
    //   task-010: CategoryDao ✅
    //   task-011: VaultDao ✅
    //   task-012: HistoryDao ✅
    //   task-021: SyncQueueDao ✅

    companion object {

        private const val DATABASE_NAME = "securevault.db"

        @Volatile
        private var INSTANCE: AppDatabase? = null

        /**
         * Returns the singleton database instance, creating it if necessary.
         *
         * @param context Application context
         * @param passphrase SQLCipher AES-256 passphrase from KeystoreManager.
         *                   Caller must zero the array after this call.
         *                   — Security_Requirements.md §9.1 key generation
         *
         * SQLCipher SupportFactory wraps the Room SQLiteOpenHelper to provide
         * transparent full-database AES-256-CBC encryption per ADR-02.
         */
        fun getInstance(context: Context, passphrase: ByteArray): AppDatabase {
            return INSTANCE ?: synchronized(this) {
                INSTANCE ?: buildDatabase(context, passphrase).also {
                    INSTANCE = it
                }
            }
        }

        private fun buildDatabase(context: Context, passphrase: ByteArray): AppDatabase {
            // SQLCipher PRAGMA hook — Security_Requirements.md §9.1:
            //   "PRAGMA secure_delete = ON" prevents plaintext password remnants
            //   from residing in temporary system directories after deletes.
            val pragmaHook = object : SQLiteDatabaseHook {
                override fun preKey(database: net.sqlcipher.database.SQLiteDatabase) {
                    // No pre-key operations required
                }

                override fun postKey(database: net.sqlcipher.database.SQLiteDatabase) {
                    database.execSQL("PRAGMA secure_delete = ON;")
                    database.execSQL("PRAGMA foreign_keys = ON;")
                }
            }

            val factory: SupportSQLiteOpenHelper.Factory =
                SupportFactory(passphrase, pragmaHook)

            return Room.databaseBuilder(
                context.applicationContext,
                AppDatabase::class.java,
                DATABASE_NAME
            )
                .openHelperFactory(factory)     // Attach SQLCipher encryption factory
                .fallbackToDestructiveMigration() // Dev-only; replaced with migrations in production
                // Migration v1 → v2 added via .addMigrations(MIGRATION_1_2) when required
                // — Database_Schema.md §7 Migration Strategy
                .build()
        }

        /**
         * Clears the singleton instance. Used only in tests.
         * Test builds use Room.inMemoryDatabaseBuilder() directly —
         * see Testing_Strategy.md §Appendix 1 (Room In-Memory database helper).
         */
        @Suppress("unused")
        fun clearInstance() {
            INSTANCE = null
        }
    }
}
